class QueryBuilder():
    async def build_leaderboard_up_and_comers(year=2025, quarter=4, first=100, engagement_type='bbp', user_type='individual'):
        query = {
        "operationName":"UpAndComersByEngagementTypeLeaderboardCard",
        "variables":{"year":year,"quarter":quarter,"first":first,"engagement_type":engagement_type,"user_type":user_type,"key":"UP_AND_COMERS_BY_ENGAGEMENT_TYPE","product_area":"leaderboard","product_feature":"details"},
        "query":"query UpAndComersByEngagementTypeLeaderboardCard($year: Int!, $quarter: Int, $first: Int, $user_type: String, $engagement_type: String, $key: LeaderboardKeyEnum!, $filter: String) {\n  collective_leaderboard_entries: leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: \"collective\"\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...UpAndComersByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: $user_type\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...UpAndComersByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    username\n    name\n    profile_picture(size: medium)\n    mark_as_company_on_leaderboards\n    leaderboard_entry(\n      key: $key\n      year: $year\n      quarter: $quarter\n      filter: $filter\n      user_type: $user_type\n      engagement_type: $engagement_type\n    ) {\n      ...UpAndComersByEngagementTypeLeaderboardFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SharedLeaderboardFragment on LeaderboardEntryInterface {\n  id\n  rank\n  previous_rank\n  user {\n    id\n    username\n    profile_picture(size: medium)\n    __typename\n  }\n  __typename\n}\n\nfragment UpAndComersByEngagementTypeLeaderboardFragment on UpAndComersByEngagementTypeLeaderboardEntry {\n  ...SharedLeaderboardFragment\n  reputation\n  __typename\n}\n"
        }
        return query

    async def build_leaderboard_highest_rep(year=2025, quarter=4, first=100, engagement_type='bbp', user_type='individual'):
        query = {
            "operationName":"HighestReputationByEngagementTypeLeaderboardCard",
            "variables":{"year":year,"quarter":quarter,"first":first,"engagement_type":engagement_type,"user_type":user_type,"key":"HIGHEST_REPUTATION_BY_ENGAGEMENT_TYPE","product_area":"leaderboard","product_feature":"details"},
            "query":"query HighestReputationByEngagementTypeLeaderboardCard($year: Int!, $quarter: Int, $first: Int, $engagement_type: String, $user_type: String, $key: LeaderboardKeyEnum!, $filter: String) {\n  collective_leaderboard_entries: leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: \"collective\"\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...HighestReputationByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: $user_type\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...HighestReputationByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    username\n    name\n    profile_picture(size: medium)\n    mark_as_company_on_leaderboards\n    leaderboard_entry(\n      key: $key\n      year: $year\n      quarter: $quarter\n      filter: $filter\n      engagement_type: $engagement_type\n      user_type: $user_type\n    ) {\n      ...HighestReputationByEngagementTypeLeaderboardFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SharedLeaderboardFragment on LeaderboardEntryInterface {\n  id\n  rank\n  previous_rank\n  user {\n    id\n    username\n    profile_picture(size: medium)\n    __typename\n  }\n  __typename\n}\n\nfragment HighestReputationByEngagementTypeLeaderboardFragment on HighestReputationByEngagementTypeLeaderboardEntry {\n  ...SharedLeaderboardFragment\n  reputation\n  signal\n  impact\n  __typename\n}\n"
        }
        return query

    async def build_leaderboard_most_upvoted(year=2025, quarter=4, first=100, engagement_type='bbp', user_type='individual'):
        query = {
            "operationName":"MostUpvotedByEngagementTypeLeaderboardCard",
            "variables":{"year":year,"quarter":quarter,"first":first,"engagement_type":engagement_type,"user_type":user_type,"key":"HACKTIVITY_UPVOTES_BY_ENGAGEMENT_TYPE","product_area":"leaderboard","product_feature":"details"},
            "query":"query MostUpvotedByEngagementTypeLeaderboardCard($year: Int!, $quarter: Int, $first: Int, $user_type: String, $engagement_type: String, $key: LeaderboardKeyEnum!, $filter: String) {\n  collective_leaderboard_entries: leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: \"collective\"\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...MostUpvotedByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: $user_type\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...MostUpvotedByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    username\n    name\n    profile_picture(size: medium)\n    mark_as_company_on_leaderboards\n    leaderboard_entry(\n      key: $key\n      year: $year\n      quarter: $quarter\n      filter: $filter\n      user_type: $user_type\n      engagement_type: $engagement_type\n    ) {\n      ...MostUpvotedByEngagementTypeLeaderboardFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SharedLeaderboardFragment on LeaderboardEntryInterface {\n  id\n  rank\n  previous_rank\n  user {\n    id\n    username\n    profile_picture(size: medium)\n    __typename\n  }\n  __typename\n}\n\nfragment MostUpvotedByEngagementTypeLeaderboardFragment on HacktivityUpvotesByEngagementTypeLeaderboardEntry {\n  ...SharedLeaderboardFragment\n  votes\n  __typename\n}\n"
        }
        return query

    async def build_leaderboard_OWASP(year=2025, quarter=4, first=100, engagement_type='bbp', user_type='individual'):
        query = {
            {"operationName":"OwaspTopTenByEngagementTypeLeaderboardCard",
             "variables":{"year":year,"quarter":quarter,"first":first,"engagement_type":engagement_type,"user_type":user_type,"key":"OWASP_TOP_10_BY_ENGAGEMENT_TYPE","filter":"a1","product_area":"leaderboard","product_feature":"details"},
             "query":"query OwaspTopTenByEngagementTypeLeaderboardCard($year: Int!, $quarter: Int, $first: Int, $user_type: String, $engagement_type: String, $key: LeaderboardKeyEnum!, $filter: String) {\n  collective_leaderboard_entries: leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: \"collective\"\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...OwaspTopTenByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: $user_type\n    engagement_type: $engagement_type\n  ) {\n    edges {\n      node {\n        ...OwaspTopTenByEngagementTypeLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    username\n    name\n    profile_picture(size: medium)\n    mark_as_company_on_leaderboards\n    leaderboard_entry(\n      key: $key\n      year: $year\n      quarter: $quarter\n      filter: $filter\n      user_type: $user_type\n      engagement_type: $engagement_type\n    ) {\n      ...OwaspTopTenByEngagementTypeLeaderboardFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SharedLeaderboardFragment on LeaderboardEntryInterface {\n  id\n  rank\n  previous_rank\n  user {\n    id\n    username\n    profile_picture(size: medium)\n    __typename\n  }\n  __typename\n}\n\nfragment OwaspTopTenByEngagementTypeLeaderboardFragment on OwaspTopTenByEngagementTypeLeaderboardEntry {\n  ...SharedLeaderboardFragment\n  reputation\n  signal\n  impact\n  __typename\n}\n"}
        }
        return query

    async def build_leaderboard_CTF_talent(year=2025, quarter=4, first=100, engagement_type='bbp', user_type='individual'):
        query = {
            "operationName":"CtfPointsLeaderboardCard",
            "variables":{"year":year,"quarter":quarter,"first":first,"engagement_type":engagement_type,"user_type":user_type,"key":"CTF_POINTS","product_area":"leaderboard","product_feature":"details"},
            "query":"query CtfPointsLeaderboardCard($year: Int!, $quarter: Int, $first: Int, $key: LeaderboardKeyEnum!, $filter: String, $user_type: String) {\n  leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: $user_type\n  ) {\n    edges {\n      node {\n        ...CtfPointsLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    username\n    name\n    profile_picture(size: medium)\n    mark_as_company_on_leaderboards\n    leaderboard_entry(\n      key: $key\n      year: $year\n      quarter: $quarter\n      filter: $filter\n      user_type: $user_type\n    ) {\n      ...CtfPointsLeaderboardFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SharedLeaderboardFragment on LeaderboardEntryInterface {\n  id\n  rank\n  previous_rank\n  user {\n    id\n    username\n    profile_picture(size: medium)\n    __typename\n  }\n  __typename\n}\n\nfragment CtfPointsLeaderboardFragment on CtfPointsLeaderboardEntry {\n  ...SharedLeaderboardFragment\n  points\n  __typename\n}\n"
        }
        return query

    async def build_leaderboard_country(year=2025, quarter=4, first=100, engagement_type='bbp', user_type='individual'):
        query = {
            "operationName":"CountryLeaderboardCard",
            "variables":{"year":year,"quarter":quarter,"first":first,"engagement_type":engagement_type,"user_type":user_type,"key":"HIGHEST_REPUTATION_BY_COUNTRY","filter":"US","product_area":"leaderboard","product_feature":"details"},
            "query":"query CountryLeaderboardCard($year: Int!, $quarter: Int, $first: Int, $key: LeaderboardKeyEnum!, $filter: String, $user_type: String) {\n  leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: $user_type\n  ) {\n    edges {\n      node {\n        ...CountryLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    username\n    name\n    profile_picture(size: medium)\n    mark_as_company_on_leaderboards\n    country\n    leaderboard_entry(\n      key: $key\n      year: $year\n      quarter: $quarter\n      filter: $filter\n      user_type: $user_type\n    ) {\n      ...CountryLeaderboardFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SharedLeaderboardFragment on LeaderboardEntryInterface {\n  id\n  rank\n  previous_rank\n  user {\n    id\n    username\n    profile_picture(size: medium)\n    __typename\n  }\n  __typename\n}\n\nfragment CountryLeaderboardFragment on HighestReputationByCountryLeaderboardEntry {\n  ...SharedLeaderboardFragment\n  reputation\n  signal\n  impact\n  __typename\n}\n"
        }
        return query

    async def build_leaderboard_pentesters(pagesize=100):
        query = {
            "operationName":"DirectoryPentestersPageQuery",
            "variables":{"pageSize":pagesize,"product_area":"leaderboard","product_feature":"details","cursor":"MjU"},
            "query":"query DirectoryPentestersPageQuery($pageSize: Int!, $cursor: String) {\n  pentester_profiles(\n    where: {state: {_eq: approved}, visible_in_directory: {_eq: true}}\n    order_by: {pentest_activity: {_direction: DESC}}\n    first: $pageSize\n    after: $cursor\n  ) {\n    pageInfo {\n      endCursor\n      hasNextPage\n      __typename\n    }\n    edges {\n      node {\n        id\n        user {\n          id\n          ...PentesterItemDetailedUser\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    __typename\n  }\n}\n\nfragment PentesterItemDetailedUser on User {\n  id\n  name\n  username\n  hackerone_agent\n  email_alias\n  linkedin_handle\n  profile_picture(size: medium)\n  signal\n  impact\n  reputation\n  hacker_skills(where: {skill: {approved: {_eq: true}}}) {\n    nodes {\n      id\n      skill {\n        id\n        database_id: _id\n        name\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  pentester_profile {\n    id\n    name\n    residence\n    completed_pentests_number\n    __typename\n  }\n  __typename\n}\n"
        }
        return query

    async def build_leaderboard_asset_types(year=2025, quarter=4, first=100, engagement_type='bbp', user_type='individual'):
        query = {
            "operationName":"AssetTypesLeaderboardCard",
            "variables":{"year":year,"quarter":quarter,"first":first,"engagement_type":engagement_type,"user_type":user_type,"key":"ASSET_TYPES","filter":"WEB_APP","product_area":"leaderboard","product_feature":"details"},
            "query":"query AssetTypesLeaderboardCard($year: Int!, $quarter: Int, $first: Int, $key: LeaderboardKeyEnum!, $filter: String, $user_type: String) {\n  leaderboard_entries(\n    key: $key\n    year: $year\n    quarter: $quarter\n    first: $first\n    filter: $filter\n    user_type: $user_type\n  ) {\n    edges {\n      node {\n        ...AssetTypesLeaderboardFragment\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  me {\n    id\n    username\n    name\n    profile_picture(size: medium)\n    mark_as_company_on_leaderboards\n    leaderboard_entry(\n      key: $key\n      year: $year\n      quarter: $quarter\n      filter: $filter\n      user_type: $user_type\n    ) {\n      ...AssetTypesLeaderboardFragment\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SharedLeaderboardFragment on LeaderboardEntryInterface {\n  id\n  rank\n  previous_rank\n  user {\n    id\n    username\n    profile_picture(size: medium)\n    __typename\n  }\n  __typename\n}\n\nfragment AssetTypesLeaderboardFragment on AssetTypesLeaderboardEntry {\n  ...SharedLeaderboardFragment\n  reputation\n  signal\n  impact\n  __typename\n}\n"
        }

    async def build_hacktivity_search_query(query_string="disclosed:true", size=100, offset=0, sort_field="disclosed_at", sort_direction="ASC"):
        query = {
            "operationName": "HacktivitySearchQuery",
            "variables": {
                "queryString": query_string,
                "size": size,
                "from": offset,
                "sort": {"field": sort_field, "direction": sort_direction},
                "product_area": "hacktivity",
                "product_feature": "overview",
            },
            "query": "query HacktivitySearchQuery($queryString: String!, $from: Int, $size: Int, $sort: SortInput!) {\n  me {\n    id\n    __typename\n  }\n  search(\n    index: CompleteHacktivityReportIndex\n    query_string: $queryString\n    from: $from\n    size: $size\n    sort: $sort\n  ) {\n    __typename\n    total_count\n    nodes {\n      __typename\n      ... on HacktivityDocument {\n        id\n        _id\n        reporter {\n          id\n          username\n          name\n          __typename\n        }\n        cve_ids\n        cwe\n        severity_rating\n        upvoted: upvoted_by_current_user\n        public\n        report {\n          id\n          databaseId: _id\n          title\n          substate\n          url\n          disclosed_at\n          report_generated_content {\n            id\n            hacktivity_summary\n            __typename\n          }\n          __typename\n        }\n        votes\n        team {\n          id\n          handle\n          name\n          medium_profile_picture: profile_picture(size: medium)\n          url\n          currency\n          __typename\n        }\n        total_awarded_amount\n        latest_disclosable_action\n        latest_disclosable_activity_at\n        submitted_at\n        disclosed\n        has_collaboration\n        collaborators {\n          id\n          username\n          name\n          __typename\n        }\n        __typename\n      }\n    }\n  }\n}\n"
        }
        return query
    
    async def build_profile_stats_query(username, snapshotType="last_90_days"):
        query = {
            "operationName":"UserProfileStatsCardSnapshot",
            "variables":{"username":username,"snapshotType":snapshotType,"product_area":"leaderboard","product_feature":"details"},
            "query":"query UserProfileStatsCardSnapshot($username: String!, $snapshotType: UserStatisticsSnapshotTypeEnum!) {\n  user(username: $username) {\n    id\n    statistics_snapshot(snapshot_type: $snapshotType) {\n      id\n      signal\n      signal_percentile\n      impact\n      impact_percentile\n      reputation\n      rank\n      __typename\n    }\n    __typename\n  }\n}\n"
        }
        return query

    async def build_profile_hacktivity_query(querystring="reporter:(\"godiego\")", size=5, offset=0, sort={"field":"latest_disclosable_activity_at","direction":"DESC"}):
        query = {
            "operationName":"HacktivitySearchQuery",
            "variables":{"queryString":querystring,"size":size,"from":offset,"sort":sort,"product_area":"leaderboard","product_feature":"details"},
            "query":"query HacktivitySearchQuery($queryString: String!, $from: Int, $size: Int, $sort: SortInput!) {\n  me {\n    id\n    __typename\n  }\n  search(\n    index: CompleteHacktivityReportIndex\n    query_string: $queryString\n    from: $from\n    size: $size\n    sort: $sort\n  ) {\n    __typename\n    total_count\n    nodes {\n      __typename\n      ... on HacktivityDocument {\n        id\n        _id\n        reporter {\n          id\n          username\n          name\n          __typename\n        }\n        cve_ids\n        cwe\n        severity_rating\n        upvoted: upvoted_by_current_user\n        public\n        report {\n          id\n          databaseId: _id\n          title\n          substate\n          url\n          disclosed_at\n          report_generated_content {\n            id\n            hacktivity_summary\n            __typename\n          }\n          __typename\n        }\n        votes\n        team {\n          id\n          handle\n          name\n          medium_profile_picture: profile_picture(size: medium)\n          url\n          currency\n          __typename\n        }\n        total_awarded_amount\n        latest_disclosable_action\n        latest_disclosable_activity_at\n        submitted_at\n        disclosed\n        has_collaboration\n        collaborators {\n          id\n          username\n          name\n          __typename\n        }\n        __typename\n      }\n    }\n  }\n}\n"
        }
        return query
    
    async def build_profile_thanks_query(username="godiego", pagesize=5):
        query = {
            "operationName":"UserProfileThanks",
            "variables":{"username":username,"pageSize":pagesize,"product_area":"leaderboard","product_feature":"details"},
            "query":"query UserProfileThanks($username: String!, $cursor: String, $pageSize: Int!) {\n  user(username: $username) {\n    id\n    user_display_options {\n      show_private_team_thanks\n      __typename\n    }\n    username\n    thanks_items_total_count\n    thanks_items(first: $pageSize, after: $cursor) {\n      pageInfo {\n        hasNextPage\n        endCursor\n        __typename\n      }\n      edges {\n        node {\n          id\n          ...ThanksItem\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment ThanksItem on ThanksItem {\n  id\n  rank\n  report_count\n  total_report_count\n  reputation\n  team {\n    id\n    handle\n    name\n    state\n    url\n    profile_picture(size: medium)\n    ...TeamLinkMiniProfileComponent\n    __typename\n  }\n  __typename\n}\n\nfragment TeamLinkMiniProfileComponent on Team {\n  id\n  handle\n  name\n  __typename\n}\n"
        }
        return query
    
    async def build_profile_testimonials_query(username="godiego", count=6):
        query = {
            "operationName":"UserProfileTestimonialList",
            "variables":{"username":username,"count":count,"product_area":"leaderboard","product_feature":"details"},
            "query":"query UserProfileTestimonialList($username: String!, $count: Int!, $cursor: String) {\n  user(username: $username) {\n    id\n    testimonials(\n      first: $count\n      after: $cursor\n      where: {visible_on_user_profile: {_eq: true}}\n      order_by: {survey_rating: {completed_at: {_direction: DESC}}}\n    ) {\n      pageInfo {\n        endCursor\n        hasNextPage\n        __typename\n      }\n      edges {\n        node {\n          id\n          key\n          rating\n          public_comment\n          survey_rating {\n            id\n            type\n            completed_at\n            created_at\n            team {\n              id\n              name\n              profile_picture(size: small)\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"
        }
        return query
    
    async def build_profile_info_query(username="godiego"):
        query = {
            "operationName":"UserProfilePageQuery",
            "variables":{"resourceIdentifier":username,"product_area":"leaderboard","product_feature":"details"},
            "query":"query UserProfilePageQuery($resourceIdentifier: String!) {\n  me {\n    id\n    username\n    ...UserProfileMe\n    ...UserProfileCardMe\n    ...UserStatsMe\n    __typename\n  }\n  user(username: $resourceIdentifier) {\n    id\n    username\n    name\n    intro\n    profileActivated: profile_activated\n    pentester_profile {\n      id\n      ...PentestsPentesterProfile\n      __typename\n    }\n    user_streak {\n      id\n      length\n      start_date\n      end_date\n      __typename\n    }\n    ...UserProfileUser\n    ...UserProfileCardUser\n    ...CreditsUser\n    ...BadgesUser\n    ...ReviewUser\n    ...UserStatsUser\n    __typename\n  }\n  ...UserProfileCardIdV\n}\n\nfragment UserProfileMe on User {\n  id\n  username\n  __typename\n}\n\nfragment UserProfileUser on User {\n  id\n  username\n  __typename\n}\n\nfragment UserProfileCardUser on User {\n  id\n  created_at\n  location\n  website\n  bio\n  name\n  username\n  profile_picture(size: large)\n  bugcrowd_handle\n  hack_the_box_handle\n  github_handle\n  gitlab_handle\n  linkedin_handle\n  twitter_handle\n  cleared\n  verified\n  open_for_employment\n  mark_as_company_on_leaderboards\n  ...FollowUser\n  __typename\n}\n\nfragment FollowUser on User {\n  id\n  followed\n  __typename\n}\n\nfragment UserProfileCardMe on User {\n  id\n  __typename\n}\n\nfragment UserProfileCardIdV on Query {\n  id_verification {\n    status\n    __typename\n  }\n  __typename\n}\n\nfragment PentestsPentesterProfile on PentesterProfile {\n  id\n  completed_pentests_number\n  __typename\n}\n\nfragment CreditsUser on User {\n  id\n  username\n  resolved_report_count\n  thanks_items_total_count\n  __typename\n}\n\nfragment BadgesUser on User {\n  id\n  username\n  badges(first: 3) {\n    edges {\n      awarded_at\n      node {\n        id\n        name\n        image_path\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment ReviewUser on User {\n  id\n  public_reviews(first: 5) {\n    edges {\n      node {\n        id\n        public_feedback\n        team {\n          id\n          name\n          handle\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment UserStatsUser on User {\n  id\n  username\n  __typename\n}\n\nfragment UserStatsMe on User {\n  id\n  __typename\n}\n"
        }
        return query